#!/bin/sh

# Default programs
export EDITOR="emacs"
export PAGER="less"
export TERMINAL="kitty"
export BROWSER="firefox"

# XDG Dirs
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"

# Runtime
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# Config
export INPUTRC="$XDG_CONFIG_HOME/readline/inpurc"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/shell/starship"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk_2.0/gtkrc"

# Data

# Cache
export HISTFILE="$XDG_CACHE_HOME/bash/history"
export LESSHISTFILE=-

# Add directories to $PATH
export PATH="${PATH}:$XDG_BIN_HOME"
