#!/bin/sh

[[ -f ~/.config/X11/Xresources ]] && xrdb -merge ~/.config/X11/Xresources
xset r rate 300 50
setxkbmap fr
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x mpd > /dev/null || mpd &
launch_statusbar &
setbg &

exec bspwm
